package com.bssys.jsf;

public enum MainMenuItemEnum {
  TRANSFER_LIST, TRANSFER_NEW, TRANSFER_PAY,
  MESSAGE_ADMIN, MESSAGE_AGENT, MESSAGE_INBOX, MESSAGE_AGENT_INBOX,
  REPORT_FINANCE, REPORT_MUTUAL, REPORT_OPERATION,
  DICTIONARY_STOPLIST, DICTIONARY_APERS, DICTIONARY_DEST_POINTS,
  DICTIONARY_LAW, DICTIONARY_CLIENTS, DICTIONARY_PROPS,
  SERVICE_ABS, SERVICE_CRYPTO, SERVICE_PASSWORD, SERVICE_USERMANUAL,
  ADMIN_AGENTS, ADMIN_AGENTS_ACTIVE, ADMIN_AGENTS_DELETED,
  ADMIN_JOURNALS, ADMIN_CERTIFICATE_REQUEST, REPORT_PSPAYMENTS, ADMIN_ADDITIONAL_COMMISSIONS,
  PAYLEGAL_LIST, REPORT_READY
}
